services:
  nadin.api:
    image: nadin.api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nadin-api
    environment:
      "ASPNETCORE_URLS": "http://+"
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ConnectionStrings__Default": "Server=nadin-sql;Database=NadinSoftDb;User Id=SA;Password=NadinDbPass1234;MultipleActiveResultSets=true;encrypt=false"
    ports:
      - "5000:80"
    depends_on:
      - nadin-sql
      - nadin-seq
  
  nadin-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nadin-sql
    environment:
      SA_PASSWORD: "NadinDbPass1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/data
  
  nadin-seq:
    image: datalust/seq:latest
    container_name: nadin-seq
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=AdminPass123
    volumes:
      - seq-data:/data

volumes:
  sql-data:
  seq-data: