services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nadinsoft-sql
    environment:
      SA_PASSWORD: "Your_strong_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: